/*
	== DO NOT EDIT THIS FILE! ==
	This is necessary to keep paths correct for the minification process
*/
enyo.depends(
	"IconButton.js",
	"HDialPicker.js",
	"CartPrice.js",
	"ContactForm.js",
	"ItemImageView.js"
);
